name: Docker Image

on:
  push:
    branches: 
      - "main"  

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get the version number
      id: version
      run: |
        VERSION_TAG="v$(date +'%Y%m%d%H%M%S')"  # Usando la fecha como ejemplo, pero puedes incrementarlo manualmente

        echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV  # Exporta la versión para usarla en pasos posteriores

    - name: Build and push Docker image
      run: |
        LATEST_TAG="latest"

        docker build . --file Dockerfile --tag epgarzonr/index:${VERSION_TAG} --tag epgarzonr/index:${LATEST_TAG}
        
        # Hacer push de las imágenes a DockerHub
        docker push epgarzonr/index:${VERSION_TAG}
        docker push epgarzonr/index:${LATEST_TAG}

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22 
        
        script: |
          sudo apt update -y
          sudo apt install -y docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user

          sudo docker pull epgarzonr/index:latest

          sudo docker ps -q --filter "name=index" | grep -q . && docker stop index && docker rm index || true
          
          sudo docker run -d --name index -p 80:80 epgarzonr/index:latest
